#!/usr/bin/env ruby

require "hue_conference"

hue = Ruhue.discover

client = Ruhue::Client.new(hue, "substantial")

if client.registered?
  puts "It appears your already registered with the Hub. Play away!"
elsif client.register("ruhue")
  puts "A new application has been registered with the Hub as #{client.username}. Play away!"
end

manifest = HueConference::LightManifest.new(client)
manifest.build_manifest

my_light = manifest.lights.select do |light|
  light.name == 'Test Lamp 1'
end.first

on = true

while true do

  sleep(1)
  if on
    on = false
    my_light.turn_off
  else
    on = true
    my_light.turn_on
  end
end
