#!/usr/bin/env ruby

require "hue_conference"

hue = Ruhue.discover

client = Ruhue::Client.new(hue, "substantial")

if client.registered?
  puts "It appears your already registered with the Hub. Play away!"
elsif client.register("ruhue")
  puts "A new application has been registered with the Hub as #{client.username}. Play away!"
end

manifest = HueConference::LightManifest.new(client)

my_light = manifest.lights.select do |light|
  light.name == 'Turf Indoor'
end.first

loop do
  sleep(1)
  my_light.toggle
end

